
// This file is generated automatically during PYLON build process
// DO NOT EDIT

#define PYLON_VERSION_MAJOR          4
#define PYLON_VERSION_MINOR          0
#define PYLON_VERSION_SUBMINOR       1
#define PYLON_VERSION_BUILD          3425
#define PYLON_VERSIONSTRING_MAJOR    "4"
#define PYLON_VERSIONSTRING_MINOR    "0"
#define PYLON_VERSIONSTRING_SUBMINOR "1"
#define PYLON_VERSIONSTRING_BUILD    "3425"
#define PYLON_VERSIONSTRING_SUFFIX    ""

#define PYLON_VERSIONSTRING_COMMENT  "20130902 1115;GVMB0001;VC_GVD"
