//-----------------------------------------------------------------------------
//  Basler Data Processing SDK
//  Copyright (c) 2021-2022 Basler AG
//  http://www.baslerweb.com
//  Author:  BR
//-----------------------------------------------------------------------------
//
// This file is autogenerated. Changes will be overwritten.
// File contains pylon data processing version defines.

#pragma once

#define PYLON_DATAPROCESSING_VERSION_MAJOR           1
#define PYLON_DATAPROCESSING_VERSION_MINOR           1
#define PYLON_DATAPROCESSING_VERSION_SUBMINOR        1
#define PYLON_DATAPROCESSING_VERSION_BUILD           4707

#define PYLON_DATAPROCESSING_VERSIONSTRING_MAJOR     "1"
#define PYLON_DATAPROCESSING_VERSIONSTRING_MINOR     "1"
#define PYLON_DATAPROCESSING_VERSIONSTRING_SUBMINOR  "1"
#define PYLON_DATAPROCESSING_VERSIONSTRING_BUILD     "4707"
#define PYLON_DATAPROCESSING_VERSIONSTRING_EXTENSION "4707"

#define PYLON_DATAPROCESSING_GIT_REVISION            "b3a32053ac44b090a78837faca8dabc3dfa05558"
#define PYLON_DATAPROCESSING_VERSION_SUFFIX          "_v1_1"
