//-----------------------------------------------------------------------------
//  Basler Data Processing SDK
//  Copyright (c) 2021-2022 Basler AG
//  http://www.baslerweb.com
//  Author:  BR
//-----------------------------------------------------------------------------
//
// This file is autogenerated. Changes will be overwritten.
// File contains pylon data processing version defines.

#pragma once

#define PYLON_DATAPROCESSING_VERSION_MAJOR           1
#define PYLON_DATAPROCESSING_VERSION_MINOR           0
#define PYLON_DATAPROCESSING_VERSION_SUBMINOR        0
#define PYLON_DATAPROCESSING_VERSION_BUILD           4095

#define PYLON_DATAPROCESSING_VERSIONSTRING_MAJOR     "1"
#define PYLON_DATAPROCESSING_VERSIONSTRING_MINOR     "0"
#define PYLON_DATAPROCESSING_VERSIONSTRING_SUBMINOR  "0"
#define PYLON_DATAPROCESSING_VERSIONSTRING_BUILD     "4095"
#define PYLON_DATAPROCESSING_VERSIONSTRING_EXTENSION "4095"

#define PYLON_DATAPROCESSING_GIT_REVISION            "ec9de33403c26bd5af084e007263c6eb1cfc840b"
#define PYLON_DATAPROCESSING_VERSION_SUFFIX          "_v1_0"
